# Creates a Desktop shortcut for Trawl.  -Remove deletes it.  -StartMenu adds one there too.
param([switch]$Remove, [switch]$StartMenu)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$desktop = [Environment]::GetFolderPath('Desktop')
$startDir = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs'

$targets = @((Join-Path $desktop 'Trawl.lnk'))
if ($StartMenu) { $targets += (Join-Path $startDir 'Trawl.lnk') }

if ($Remove) {
    foreach ($t in $targets) {
        if (Test-Path $t) { Remove-Item $t -Force; Write-Host "Removed $t" }
    }
    return
}

$wsh = New-Object -ComObject WScript.Shell
foreach ($t in $targets) {
    $sc = $wsh.CreateShortcut($t)
    # wscript.exe + the VBS shim is what keeps the console from ever appearing
    $sc.TargetPath       = "$env:SystemRoot\System32\wscript.exe"
    $sc.Arguments        = """$root\Trawl.vbs"""
    $sc.WorkingDirectory = $root
    $sc.Description      = 'Trawl - generate, review, and post AI social posts'
    # Own icon, generated by make-icon.py. Matches the inline SVG favicon in ui/index.html so the
    # shortcut, the app window and the taskbar entry all show the same mark.
    $icon = Join-Path $root 'trawl.ico'
    if (-not (Test-Path $icon)) {
        Write-Host "trawl.ico missing - generating it..." -ForegroundColor Yellow
        $py = (Get-Command python -ErrorAction SilentlyContinue).Source
        if ($py) { & $py (Join-Path $root 'make-icon.py') | Out-Null }
    }
    $sc.IconLocation = if (Test-Path $icon) { "$icon,0" } else { "$env:SystemRoot\System32\shell32.dll,44" }
    $sc.Save()
    Write-Host "Created $t" -ForegroundColor Green
}

Write-Host "`nDouble-click Trawl on your Desktop. No console, no terminal." -ForegroundColor Cyan
